version: '3'

services:
  newsnow:
    container_name: newsnow
    restart: always
    build:
      context: . # 构建上下文，通常是 Dockerfile 所在的目录
      dockerfile: Dockerfile # Dockerfile 的名称
    ports:
      - '4444:4444'
    environment:
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
